### PR TITLE
Demonstrator for supporting Units of Measurement #3

### PR DESCRIPTION
**Pull request by tahirs95**
Demonstrator for supporting Units of Measurement #3

### CODE REVIEW

**Comment by tahirs95** [comment]
failure
- test_lineOK is failing because getHeading is returning value in radians.
error
- Above errors are due to environmental reasons not because of source code.

**Comment by IanMayo** [comment]
Ok @tahirs95 - I've made some changes.  I need to do some more refactoring (the logic to parse a line of text should sit in REPFile, not in State  - since State is a generic object that may come from a range of line-styles).

But, I'd appreciate you helping me further with `pint`:

* [ ] The pint documentation says we should have just one instance of UnitRegistry.  Could you create a class to contain that unitregistory, and amend the code so we just refer to that one instance.  That class should also declare meters_per_second, to avoid us having to type meter / second
* [ ] Could you also find a way to indicate in the `setHeading()` method parameters that the value it takes should be of type `Quantity`?  Or, better still, indicating it should be a `Quantity` of type `Angle`.

**Comment by IanMayo** [comment]
That last commit is quite _gnarly_ Python for me.  I look forward to trying it out locally.

**Review by IanMayo — APPROVED** [review]
We still have some refactoring of State & REP parsing, but we've got a useful start for how to use units of measurement.

**Pull request merged**
